/*Warren Quattrocchi
  CSC 152
  2025
  9/25/2019

  Takes an array of 64 unsigned chars generated by perm152
  and runs it through perm152's inverse function
*/


#include <stdio.h>
#include <inttypes.h>
#include <string.h>

//function headers
static void update(uint32_t * w, uint32_t * x, uint32_t *y, uint32_t *z);
static uint32_t rotr(uint32_t x, int i);
void perm152inverse(unsigned char *in, unsigned char *out);

//the inverse function of perm152 as described in the homework
void perm152inverse(unsigned char *in, unsigned char *out)
{
	int i;
	uint32_t a[16];
	memcpy(a, in, sizeof(a));
	for(i = 0; i < 10; i++)
	{ 
		update(&a[3], &a[4], &a[9], &a[14]);  
		update(&a[2], &a[7], &a[8], &a[13]);
		update(&a[1], &a[6], &a[11], &a[12]);  
		update(&a[0], &a[5], &a[10], &a[15]);	
		update(&a[3], &a[7], &a[11], &a[15]);
		update(&a[2], &a[6], &a[10], &a[14]);
		update(&a[1], &a[5], &a[9], &a[13]);
		update(&a[0], &a[4], &a[8], &a[12]);	
    }
    memcpy(out, a, sizeof(a));
}

//perform the inverse operation for each operation done in perm152's update function
static void update(uint32_t * w, uint32_t * x, uint32_t * y, uint32_t *z)
{
    *x = rotr(*x, 7);
    *x = *x ^ *y;
    *y = *y - *z;

    *z = rotr(*z, 8);
    *z = *z ^ *w;
    *w = *w - *x;

    *x = rotr(*x, 12);
    *x = *x ^ *y;
    *y = *y - *z;

    *z = rotr(*z, 16);
    *z = *z ^ *w;
    *w = *w - *x;
}

//rotate a 32 bit unsigned integer x left by i
static uint32_t rotr(uint32_t x, int i)
{
    return (x >> i) | (x << (32 - i));
}


